float:
  any:
  - base_args: ['@metric']
    constructor: YugabyteDB
    disabled: false
    docker_tag: ann-benchmarks-yugabytedb
    module: ann_benchmarks.algorithms.yugabytedb
    name: yugabytedb
    run_groups:
      M-16:
        arg_groups: [{M: 16, efConstruction: 500}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
      M-24:
        arg_groups: [{M: 24, efConstruction: 500}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 800]]
