float:
  any:
  - base_args: ['@metric']
    constructor: Usearch
    disabled: false
    docker_tag: ann-benchmarks-usearch
    module: ann_benchmarks.algorithms.usearch
    name: usearch
    run_groups:
      M-24:
        arg_groups: [{M: 24, efConstruction: 500, dtype: f16}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
